/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Browser: String {
    /**
     Array of brand name and version separated by a space
      // Examples
      attributes[.browserBrands] = [" Not A;Brand 99", "Chromium 99", "Chrome 99"]
     - Note: This value is intended to be taken from the [UA client hints API](https://wicg.github.io/ua-client-hints/#interface) (`navigator.userAgentData.brands`).
     - Requires: Value type should be `[String]`
    */
    case browserBrands = "browser.brands"

    /**
     Preferred language of the user using the browser
      // Examples
      attributes[.browserLanguage] = "en"
      attributes[.browserLanguage] = "en-US"
      attributes[.browserLanguage] = "fr"
      attributes[.browserLanguage] = "fr-FR"
     - Note: This value is intended to be taken from the Navigator API `navigator.language`.
     - Requires: Value type should be `String`
    */
    case browserLanguage = "browser.language"

    /**
     A boolean that is true if the browser is running on a mobile device
     - Note: This value is intended to be taken from the [UA client hints API](https://wicg.github.io/ua-client-hints/#interface) (`navigator.userAgentData.mobile`). If unavailable, this attribute SHOULD be left unset.
     - Requires: Value type should be `Bool`
    */
    case browserMobile = "browser.mobile"

    /**
     The platform on which the browser is running
      // Examples
      attributes[.browserPlatform] = "Windows"
      attributes[.browserPlatform] = "macOS"
      attributes[.browserPlatform] = "Android"
     - Note: This value is intended to be taken from the [UA client hints API](https://wicg.github.io/ua-client-hints/#interface) (`navigator.userAgentData.platform`). If unavailable, the legacy `navigator.platform` API SHOULD NOT be used instead and this attribute SHOULD be left unset in order for the values to be consistent.
     The list of possible values is defined in the [W3C User-Agent Client Hints specification](https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform). Note that some (but not all) of these values can overlap with values in the [`os.type` and `os.name` attributes](./os.md). However, for consistency, the values in the `browser.platform` attribute should capture the exact value that the user agent provides.
     - Requires: Value type should be `String`
    */
    case browserPlatform = "browser.platform"

  }
}