/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Cicd: String {
    /**
     The kind of action a pipeline run is performing.
      // Examples
      attributes[.cicdPipelineActionName] = BUILD
      attributes[.cicdPipelineActionName] = RUN
      attributes[.cicdPipelineActionName] = SYNC
     - Requires: Value should be one of [`/output/Attributes/Cicd_attributes.swift.CicdPipelineActionNameValues`](x-source-tag://otelCicdPipelineActionNameValues) (of type `String`)
    */
    case cicdPipelineActionName = "cicd.pipeline.action.name"

    /**
     The human readable name of the pipeline within a CI/CD system.
      // Examples
      attributes[.cicdPipelineName] = "Build and Test"
      attributes[.cicdPipelineName] = "Lint"
      attributes[.cicdPipelineName] = "Deploy Go Project"
      attributes[.cicdPipelineName] = "deploy_to_environment"
     - Requires: Value type should be `String`
    */
    case cicdPipelineName = "cicd.pipeline.name"

    /**
     The result of a pipeline run.
      // Examples
      attributes[.cicdPipelineResult] = success
      attributes[.cicdPipelineResult] = failure
      attributes[.cicdPipelineResult] = timeout
      attributes[.cicdPipelineResult] = skipped
     - Requires: Value should be one of [`/output/Attributes/Cicd_attributes.swift.CicdPipelineResultValues`](x-source-tag://otelCicdPipelineResultValues) (of type `String`)
    */
    case cicdPipelineResult = "cicd.pipeline.result"

    /**
     The unique identifier of a pipeline run within a CI/CD system.
      // Examples
      attributes[.cicdPipelineRunId] = "120912"
     - Requires: Value type should be `String`
    */
    case cicdPipelineRunId = "cicd.pipeline.run.id"

    /**
     The pipeline run goes through these states during its lifecycle.
      // Examples
      attributes[.cicdPipelineRunState] = pending
      attributes[.cicdPipelineRunState] = executing
      attributes[.cicdPipelineRunState] = finalizing
     - Requires: Value should be one of [`/output/Attributes/Cicd_attributes.swift.CicdPipelineRunStateValues`](x-source-tag://otelCicdPipelineRunStateValues) (of type `String`)
    */
    case cicdPipelineRunState = "cicd.pipeline.run.state"

    /**
     The [URL](https://wikipedia.org/wiki/URL) of the pipeline run, providing the complete address in order to locate and identify the pipeline run.
      // Examples
      attributes[.cicdPipelineRunUrlFull] = "https://github.com/open-telemetry/semantic-conventions/actions/runs/9753949763?pr=1075"
     - Requires: Value type should be `String`
    */
    case cicdPipelineRunUrlFull = "cicd.pipeline.run.url.full"

    /**
     The human readable name of a task within a pipeline. Task here most closely aligns with a [computing process](https://wikipedia.org/wiki/Pipeline_(computing)) in a pipeline. Other terms for tasks include commands, steps, and procedures.
      // Examples
      attributes[.cicdPipelineTaskName] = "Run GoLang Linter"
      attributes[.cicdPipelineTaskName] = "Go Build"
      attributes[.cicdPipelineTaskName] = "go-test"
      attributes[.cicdPipelineTaskName] = "deploy_binary"
     - Requires: Value type should be `String`
    */
    case cicdPipelineTaskName = "cicd.pipeline.task.name"

    /**
     The unique identifier of a task run within a pipeline.
      // Examples
      attributes[.cicdPipelineTaskRunId] = "12097"
     - Requires: Value type should be `String`
    */
    case cicdPipelineTaskRunId = "cicd.pipeline.task.run.id"

    /**
     The result of a task run.
      // Examples
      attributes[.cicdPipelineTaskRunResult] = success
      attributes[.cicdPipelineTaskRunResult] = failure
      attributes[.cicdPipelineTaskRunResult] = timeout
      attributes[.cicdPipelineTaskRunResult] = skipped
     - Requires: Value should be one of [`/output/Attributes/Cicd_attributes.swift.CicdPipelineTaskRunResultValues`](x-source-tag://otelCicdPipelineTaskRunResultValues) (of type `String`)
    */
    case cicdPipelineTaskRunResult = "cicd.pipeline.task.run.result"

    /**
     The [URL](https://wikipedia.org/wiki/URL) of the pipeline task run, providing the complete address in order to locate and identify the pipeline task run.
      // Examples
      attributes[.cicdPipelineTaskRunUrlFull] = "https://github.com/open-telemetry/semantic-conventions/actions/runs/9753949763/job/26920038674?pr=1075"
     - Requires: Value type should be `String`
    */
    case cicdPipelineTaskRunUrlFull = "cicd.pipeline.task.run.url.full"

    /**
     The type of the task within a pipeline.
      // Examples
      attributes[.cicdPipelineTaskType] = build
      attributes[.cicdPipelineTaskType] = test
      attributes[.cicdPipelineTaskType] = deploy
     - Requires: Value should be one of [`/output/Attributes/Cicd_attributes.swift.CicdPipelineTaskTypeValues`](x-source-tag://otelCicdPipelineTaskTypeValues) (of type `String`)
    */
    case cicdPipelineTaskType = "cicd.pipeline.task.type"

    /**
     The name of a component of the CICD system.
      // Examples
      attributes[.cicdSystemComponent] = "controller"
      attributes[.cicdSystemComponent] = "scheduler"
      attributes[.cicdSystemComponent] = "agent"
     - Requires: Value type should be `String`
    */
    case cicdSystemComponent = "cicd.system.component"

    /**
     The unique identifier of a worker within a CICD system.
      // Examples
      attributes[.cicdWorkerId] = "abc123"
      attributes[.cicdWorkerId] = "10.0.1.2"
      attributes[.cicdWorkerId] = "controller"
     - Requires: Value type should be `String`
    */
    case cicdWorkerId = "cicd.worker.id"

    /**
     The name of a worker within a CICD system.
      // Examples
      attributes[.cicdWorkerName] = "agent-abc"
      attributes[.cicdWorkerName] = "controller"
      attributes[.cicdWorkerName] = "Ubuntu LTS"
     - Requires: Value type should be `String`
    */
    case cicdWorkerName = "cicd.worker.name"

    /**
     The state of a CICD worker / agent.
      // Examples
      attributes[.cicdWorkerState] = idle
      attributes[.cicdWorkerState] = busy
      attributes[.cicdWorkerState] = down
     - Requires: Value should be one of [`/output/Attributes/Cicd_attributes.swift.CicdWorkerStateValues`](x-source-tag://otelCicdWorkerStateValues) (of type `String`)
    */
    case cicdWorkerState = "cicd.worker.state"

    /**
     The [URL](https://wikipedia.org/wiki/URL) of the worker, providing the complete address in order to locate and identify the worker.
      // Examples
      attributes[.cicdWorkerUrlFull] = "https://cicd.example.org/worker/abc123"
     - Requires: Value type should be `String`
    */
    case cicdWorkerUrlFull = "cicd.worker.url.full"


    /** 
      The kind of action a pipeline run is performing.
    */
    /// - Tag: otelCicdPipelineActionNameValues
    public struct CicdPipelineActionNameValues: CustomStringConvertible {
      /**
      The pipeline run is executing a build.
      */
      public static let build = CicdPipelineActionNameValues("BUILD") 
      /**
      The pipeline run is executing.
      */
      public static let run = CicdPipelineActionNameValues("RUN") 
      /**
      The pipeline run is executing a sync.
      */
      public static let sync = CicdPipelineActionNameValues("SYNC") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The result of a pipeline run.
    */
    /// - Tag: otelCicdPipelineResultValues
    public struct CicdPipelineResultValues: CustomStringConvertible {
      /**
      The pipeline run finished successfully.
      */
      public static let success = CicdPipelineResultValues("success") 
      /**
      The pipeline run did not finish successfully, eg. due to a compile error or a failing test. Such failures are usually detected by non-zero exit codes of the tools executed in the pipeline run.
      */
      public static let failure = CicdPipelineResultValues("failure") 
      /**
      The pipeline run failed due to an error in the CICD system, eg. due to the worker being killed.
      */
      public static let error = CicdPipelineResultValues("error") 
      /**
      A timeout caused the pipeline run to be interrupted.
      */
      public static let timeout = CicdPipelineResultValues("timeout") 
      /**
      The pipeline run was cancelled, eg. by a user manually cancelling the pipeline run.
      */
      public static let cancellation = CicdPipelineResultValues("cancellation") 
      /**
      The pipeline run was skipped, eg. due to a precondition not being met.
      */
      public static let skip = CicdPipelineResultValues("skip") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The pipeline run goes through these states during its lifecycle.
    */
    /// - Tag: otelCicdPipelineRunStateValues
    public struct CicdPipelineRunStateValues: CustomStringConvertible {
      /**
      The run pending state spans from the event triggering the pipeline run until the execution of the run starts (eg. time spent in a queue, provisioning agents, creating run resources).
      */
      public static let pending = CicdPipelineRunStateValues("pending") 
      /**
      The executing state spans the execution of any run tasks (eg. build, test).
      */
      public static let executing = CicdPipelineRunStateValues("executing") 
      /**
      The finalizing state spans from when the run has finished executing (eg. cleanup of run resources).
      */
      public static let finalizing = CicdPipelineRunStateValues("finalizing") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The result of a task run.
    */
    /// - Tag: otelCicdPipelineTaskRunResultValues
    public struct CicdPipelineTaskRunResultValues: CustomStringConvertible {
      /**
      The task run finished successfully.
      */
      public static let success = CicdPipelineTaskRunResultValues("success") 
      /**
      The task run did not finish successfully, eg. due to a compile error or a failing test. Such failures are usually detected by non-zero exit codes of the tools executed in the task run.
      */
      public static let failure = CicdPipelineTaskRunResultValues("failure") 
      /**
      The task run failed due to an error in the CICD system, eg. due to the worker being killed.
      */
      public static let error = CicdPipelineTaskRunResultValues("error") 
      /**
      A timeout caused the task run to be interrupted.
      */
      public static let timeout = CicdPipelineTaskRunResultValues("timeout") 
      /**
      The task run was cancelled, eg. by a user manually cancelling the task run.
      */
      public static let cancellation = CicdPipelineTaskRunResultValues("cancellation") 
      /**
      The task run was skipped, eg. due to a precondition not being met.
      */
      public static let skip = CicdPipelineTaskRunResultValues("skip") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The type of the task within a pipeline.
    */
    /// - Tag: otelCicdPipelineTaskTypeValues
    public struct CicdPipelineTaskTypeValues: CustomStringConvertible {
      /**
      build
      */
      public static let build = CicdPipelineTaskTypeValues("build") 
      /**
      test
      */
      public static let test = CicdPipelineTaskTypeValues("test") 
      /**
      deploy
      */
      public static let deploy = CicdPipelineTaskTypeValues("deploy") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The state of a CICD worker / agent.
    */
    /// - Tag: otelCicdWorkerStateValues
    public struct CicdWorkerStateValues: CustomStringConvertible {
      /**
      The worker is not performing work for the CICD system. It is available to the CICD system to perform work on (online / idle).
      */
      public static let available = CicdWorkerStateValues("available") 
      /**
      The worker is performing work for the CICD system.
      */
      public static let busy = CicdWorkerStateValues("busy") 
      /**
      The worker is not available to the CICD system (disconnected / down).
      */
      public static let offline = CicdWorkerStateValues("offline") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}