/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Disk: String {
    /**
     The disk IO operation direction.
      // Examples
      attributes[.diskIoDirection] = read
     - Requires: Value should be one of [`/output/Attributes/Disk_attributes.swift.DiskIoDirectionValues`](x-source-tag://otelDiskIoDirectionValues) (of type `String`)
    */
    case diskIoDirection = "disk.io.direction"


    /** 
      The disk IO operation direction.
    */
    /// - Tag: otelDiskIoDirectionValues
    public struct DiskIoDirectionValues: CustomStringConvertible {
      public static let read = DiskIoDirectionValues("read") 
      public static let write = DiskIoDirectionValues("write") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}