/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Elasticsearch: String {
    /**
     Represents the human-readable identifier of the node/instance to which a request was routed.
      // Examples
      attributes[.elasticsearchNodeName] = "instance-0000000001"
     - Requires: Value type should be `String`
    */
    case elasticsearchNodeName = "elasticsearch.node.name"

  }
}