/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Enduser: String {
    /**
     Unique identifier of an end user in the system. It maybe a username, email address, or other identifier.
      // Examples
      attributes[.enduserId] = "username"
     - Note: Unique identifier of an end user in the system.

     > [!Warning]
     > This field contains sensitive (PII) information.
     - Requires: Value type should be `String`
    */
    case id = "enduser.id"

    /**
     Pseudonymous identifier of an end user. This identifier should be a random value that is not directly linked or associated with the end user's actual identity.
      // Examples
      attributes[.enduserPseudoId] = "QdH5CAWJgqVT4rOr0qtumf"
     - Note: Pseudonymous identifier of an end user.

     > [!Warning]
     > This field contains sensitive (linkable PII) information.
     - Requires: Value type should be `String`
    */
    case pseudoId = "enduser.pseudo.id"

  }
}