/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Go: String {
    /**
     The type of memory.
      // Examples
      attributes[.goMemoryType] = other
      attributes[.goMemoryType] = stack
     - Requires: Value should be one of [`/output/Attributes/Go_attributes.swift.GoMemoryTypeValues`](x-source-tag://otelGoMemoryTypeValues) (of type `String`)
    */
    case goMemoryType = "go.memory.type"


    /** 
      The type of memory.
    */
    /// - Tag: otelGoMemoryTypeValues
    public struct GoMemoryTypeValues: CustomStringConvertible {
      /**
      Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.
      */
      public static let stack = GoMemoryTypeValues("stack") 
      /**
      Memory used by the Go runtime, excluding other categories of memory usage described in this enumeration.
      */
      public static let other = GoMemoryTypeValues("other") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}