/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Graphql: String {
    /**
     The GraphQL document being executed.
      // Examples
  
   attributes[.graphqlDocument] = "query findBookById { bookById(id: ?) { name } }"
     - Note: The value may be sanitized to exclude sensitive information.
     - Requires: Value type should be `String`
    */
    case graphqlDocument = "graphql.document"

    /**
     The name of the operation being executed.
      // Examples
  
   attributes[.graphqlOperationName] = "findBookById"
     - Requires: Value type should be `String`
    */
    case graphqlOperationName = "graphql.operation.name"

    /**
     The type of the operation being executed.
      // Examples
      attributes[.graphqlOperationType] = query
      attributes[.graphqlOperationType] = mutation
      attributes[.graphqlOperationType] = subscription
     - Requires: Value should be one of [`/output/Attributes/Graphql_attributes.swift.GraphqlOperationTypeValues`](x-source-tag://otelGraphqlOperationTypeValues) (of type `String`)
    */
    case graphqlOperationType = "graphql.operation.type"


    /** 
      The type of the operation being executed.
    */
    /// - Tag: otelGraphqlOperationTypeValues
    public struct GraphqlOperationTypeValues: CustomStringConvertible {
      /**
      GraphQL query
      */
      public static let query = GraphqlOperationTypeValues("query") 
      /**
      GraphQL mutation
      */
      public static let mutation = GraphqlOperationTypeValues("mutation") 
      /**
      GraphQL subscription
      */
      public static let subscription = GraphqlOperationTypeValues("subscription") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}