/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Heroku: String {
    /**
     Unique identifier for the application
      // Examples
      attributes[.herokuAppId] = "2daa2797-e42b-4624-9322-ec3f968df4da"
     - Requires: Value type should be `String`
    */
    case herokuAppId = "heroku.app.id"

    /**
     Commit hash for the current release
      // Examples
      attributes[.herokuReleaseCommit] = "e6134959463efd8966b20e75b913cafe3f5ec"
     - Requires: Value type should be `String`
    */
    case herokuReleaseCommit = "heroku.release.commit"

    /**
     Time and date the release was created
      // Examples
      attributes[.herokuReleaseCreationTimestamp] = "2022-10-23T18:00:42Z"
     - Requires: Value type should be `String`
    */
    case herokuReleaseCreationTimestamp = "heroku.release.creation_timestamp"

  }
}