/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Hw: String {
    /**
     Design capacity in Watts-hours or Amper-hours
      // Examples
      attributes[.hwBatteryCapacity] = "9.3Ah"
      attributes[.hwBatteryCapacity] = "50Wh"
     - Requires: Value type should be `String`
    */
    case hwBatteryCapacity = "hw.battery.capacity"

    /**
     Battery [chemistry](https://schemas.dmtf.org/wbem/cim-html/2.31.0/CIM_Battery.html), e.g. Lithium-Ion, Nickel-Cadmium, etc.
      // Examples
      attributes[.hwBatteryChemistry] = "Li-ion"
      attributes[.hwBatteryChemistry] = "NiMH"
     - Requires: Value type should be `String`
    */
    case hwBatteryChemistry = "hw.battery.chemistry"

    /**
     The current state of the battery
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwBatteryStateValues`](x-source-tag://otelHwBatteryStateValues) (of type `String`)
    */
    case hwBatteryState = "hw.battery.state"

    /**
     BIOS version of the hardware component
      // Examples
      attributes[.hwBiosVersion] = "1.2.3"
     - Requires: Value type should be `String`
    */
    case hwBiosVersion = "hw.bios_version"

    /**
     Driver version for the hardware component
      // Examples
      attributes[.hwDriverVersion] = "10.2.1-3"
     - Requires: Value type should be `String`
    */
    case hwDriverVersion = "hw.driver_version"

    /**
     Type of the enclosure (useful for modular systems)
      // Examples
      attributes[.hwEnclosureType] = "Computer"
      attributes[.hwEnclosureType] = "Storage"
      attributes[.hwEnclosureType] = "Switch"
     - Requires: Value type should be `String`
    */
    case hwEnclosureType = "hw.enclosure.type"

    /**
     Firmware version of the hardware component
      // Examples
      attributes[.hwFirmwareVersion] = "2.0.1"
     - Requires: Value type should be `String`
    */
    case hwFirmwareVersion = "hw.firmware_version"

    /**
     Type of task the GPU is performing
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwGpuTaskValues`](x-source-tag://otelHwGpuTaskValues) (of type `String`)
    */
    case hwGpuTask = "hw.gpu.task"

    /**
     An identifier for the hardware component, unique within the monitored host
      // Examples
      attributes[.hwId] = "win32battery_battery_testsysa33_1"
     - Requires: Value type should be `String`
    */
    case hwId = "hw.id"

    /**
     Type of limit for hardware components
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwLimitTypeValues`](x-source-tag://otelHwLimitTypeValues) (of type `String`)
    */
    case hwLimitType = "hw.limit_type"

    /**
     RAID Level of the logical disk
      // Examples
      attributes[.hwLogicalDiskRaidLevel] = "RAID0+1"
      attributes[.hwLogicalDiskRaidLevel] = "RAID5"
      attributes[.hwLogicalDiskRaidLevel] = "RAID10"
     - Requires: Value type should be `String`
    */
    case hwLogicalDiskRaidLevel = "hw.logical_disk.raid_level"

    /**
     State of the logical disk space usage
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwLogicalDiskStateValues`](x-source-tag://otelHwLogicalDiskStateValues) (of type `String`)
    */
    case hwLogicalDiskState = "hw.logical_disk.state"

    /**
     Type of the memory module
      // Examples
      attributes[.hwMemoryType] = "DDR4"
      attributes[.hwMemoryType] = "DDR5"
      attributes[.hwMemoryType] = "LPDDR5"
     - Requires: Value type should be `String`
    */
    case hwMemoryType = "hw.memory.type"

    /**
     Descriptive model name of the hardware component
      // Examples
      attributes[.hwModel] = "PERC H740P"
      attributes[.hwModel] = "Intel(R) Core(TM) i7-10700K"
      attributes[.hwModel] = "Dell XPS 15 Battery"
     - Requires: Value type should be `String`
    */
    case hwModel = "hw.model"

    /**
     An easily-recognizable name for the hardware component
      // Examples
      attributes[.hwName] = "eth0"
     - Requires: Value type should be `String`
    */
    case hwName = "hw.name"

    /**
     Logical addresses of the adapter (e.g. IP address, or WWPN)
      // Examples
      attributes[.hwNetworkLogicalAddresses] = ["172.16.8.21", "57.11.193.42"]
     - Requires: Value type should be `[String]`
    */
    case hwNetworkLogicalAddresses = "hw.network.logical_addresses"

    /**
     Physical address of the adapter (e.g. MAC address, or WWNN)
      // Examples
      attributes[.hwNetworkPhysicalAddress] = "00-90-F5-E9-7B-36"
     - Requires: Value type should be `String`
    */
    case hwNetworkPhysicalAddress = "hw.network.physical_address"

    /**
     Unique identifier of the parent component (typically the `hw.id` attribute of the enclosure, or disk controller)
      // Examples
      attributes[.hwParent] = "dellStorage_perc_0"
     - Requires: Value type should be `String`
    */
    case hwParent = "hw.parent"

    /**
     [S.M.A.R.T.](https://wikipedia.org/wiki/S.M.A.R.T.) (Self-Monitoring, Analysis, and Reporting Technology) attribute of the physical disk
      // Examples
      attributes[.hwPhysicalDiskSmartAttribute] = "Spin Retry Count"
      attributes[.hwPhysicalDiskSmartAttribute] = "Seek Error Rate"
      attributes[.hwPhysicalDiskSmartAttribute] = "Raw Read Error Rate"
     - Requires: Value type should be `String`
    */
    case hwPhysicalDiskSmartAttribute = "hw.physical_disk.smart_attribute"

    /**
     State of the physical disk endurance utilization
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwPhysicalDiskStateValues`](x-source-tag://otelHwPhysicalDiskStateValues) (of type `String`)
    */
    case hwPhysicalDiskState = "hw.physical_disk.state"

    /**
     Type of the physical disk
      // Examples
      attributes[.hwPhysicalDiskType] = "HDD"
      attributes[.hwPhysicalDiskType] = "SSD"
      attributes[.hwPhysicalDiskType] = "10K"
     - Requires: Value type should be `String`
    */
    case hwPhysicalDiskType = "hw.physical_disk.type"

    /**
     Location of the sensor
      // Examples
      attributes[.hwSensorLocation] = "cpu0"
      attributes[.hwSensorLocation] = "ps1"
      attributes[.hwSensorLocation] = "INLET"
      attributes[.hwSensorLocation] = "CPU0_DIE"
      attributes[.hwSensorLocation] = "AMBIENT"
      attributes[.hwSensorLocation] = "MOTHERBOARD"
      attributes[.hwSensorLocation] = "PS0 V3_3"
      attributes[.hwSensorLocation] = "MAIN_12V"
      attributes[.hwSensorLocation] = "CPU_VCORE"
     - Requires: Value type should be `String`
    */
    case hwSensorLocation = "hw.sensor_location"

    /**
     Serial number of the hardware component
      // Examples
      attributes[.hwSerialNumber] = "CNFCP0123456789"
     - Requires: Value type should be `String`
    */
    case hwSerialNumber = "hw.serial_number"

    /**
     The current state of the component
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwStateValues`](x-source-tag://otelHwStateValues) (of type `String`)
    */
    case hwState = "hw.state"

    /**
     Type of tape drive operation
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwTapeDriveOperationTypeValues`](x-source-tag://otelHwTapeDriveOperationTypeValues) (of type `String`)
    */
    case hwTapeDriveOperationType = "hw.tape_drive.operation_type"

    /**
     Type of the component
     - Note: Describes the category of the hardware component for which `hw.state` is being reported. For example, `hw.type=temperature` along with `hw.state=degraded` would indicate that the temperature of the hardware component has been reported as `degraded`.
     - Requires: Value should be one of [`/output/Attributes/Hw_attributes.swift.HwTypeValues`](x-source-tag://otelHwTypeValues) (of type `String`)
    */
    case hwType = "hw.type"

    /**
     Vendor name of the hardware component
      // Examples
      attributes[.hwVendor] = "Dell"
      attributes[.hwVendor] = "HP"
      attributes[.hwVendor] = "Intel"
      attributes[.hwVendor] = "AMD"
      attributes[.hwVendor] = "LSI"
      attributes[.hwVendor] = "Lenovo"
     - Requires: Value type should be `String`
    */
    case hwVendor = "hw.vendor"


    /** 
      The current state of the battery
    */
    /// - Tag: otelHwBatteryStateValues
    public struct HwBatteryStateValues: CustomStringConvertible {
      /**
      Charging
      */
      public static let charging = HwBatteryStateValues("charging") 
      /**
      Discharging
      */
      public static let discharging = HwBatteryStateValues("discharging") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Type of task the GPU is performing
    */
    /// - Tag: otelHwGpuTaskValues
    public struct HwGpuTaskValues: CustomStringConvertible {
      /**
      Decoder
      */
      public static let decoder = HwGpuTaskValues("decoder") 
      /**
      Encoder
      */
      public static let encoder = HwGpuTaskValues("encoder") 
      /**
      General
      */
      public static let general = HwGpuTaskValues("general") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Type of limit for hardware components
    */
    /// - Tag: otelHwLimitTypeValues
    public struct HwLimitTypeValues: CustomStringConvertible {
      /**
      Critical
      */
      public static let critical = HwLimitTypeValues("critical") 
      /**
      Degraded
      */
      public static let degraded = HwLimitTypeValues("degraded") 
      /**
      High Critical
      */
      public static let highCritical = HwLimitTypeValues("high.critical") 
      /**
      High Degraded
      */
      public static let highDegraded = HwLimitTypeValues("high.degraded") 
      /**
      Low Critical
      */
      public static let lowCritical = HwLimitTypeValues("low.critical") 
      /**
      Low Degraded
      */
      public static let lowDegraded = HwLimitTypeValues("low.degraded") 
      /**
      Maximum
      */
      public static let max = HwLimitTypeValues("max") 
      /**
      Throttled
      */
      public static let throttled = HwLimitTypeValues("throttled") 
      /**
      Turbo
      */
      public static let turbo = HwLimitTypeValues("turbo") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      State of the logical disk space usage
    */
    /// - Tag: otelHwLogicalDiskStateValues
    public struct HwLogicalDiskStateValues: CustomStringConvertible {
      /**
      Used
      */
      public static let used = HwLogicalDiskStateValues("used") 
      /**
      Free
      */
      public static let free = HwLogicalDiskStateValues("free") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      State of the physical disk endurance utilization
    */
    /// - Tag: otelHwPhysicalDiskStateValues
    public struct HwPhysicalDiskStateValues: CustomStringConvertible {
      /**
      Remaining
      */
      public static let remaining = HwPhysicalDiskStateValues("remaining") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The current state of the component
    */
    /// - Tag: otelHwStateValues
    public struct HwStateValues: CustomStringConvertible {
      /**
      Degraded
      */
      public static let degraded = HwStateValues("degraded") 
      /**
      Failed
      */
      public static let failed = HwStateValues("failed") 
      /**
      Needs Cleaning
      */
      public static let needsCleaning = HwStateValues("needs_cleaning") 
      /**
      OK
      */
      public static let ok = HwStateValues("ok") 
      /**
      Predicted Failure
      */
      public static let predictedFailure = HwStateValues("predicted_failure") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Type of tape drive operation
    */
    /// - Tag: otelHwTapeDriveOperationTypeValues
    public struct HwTapeDriveOperationTypeValues: CustomStringConvertible {
      /**
      Mount
      */
      public static let mount = HwTapeDriveOperationTypeValues("mount") 
      /**
      Unmount
      */
      public static let unmount = HwTapeDriveOperationTypeValues("unmount") 
      /**
      Clean
      */
      public static let clean = HwTapeDriveOperationTypeValues("clean") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Type of the component
    */
    /// - Tag: otelHwTypeValues
    public struct HwTypeValues: CustomStringConvertible {
      /**
      Battery
      */
      public static let battery = HwTypeValues("battery") 
      /**
      CPU
      */
      public static let cpu = HwTypeValues("cpu") 
      /**
      Disk controller
      */
      public static let diskController = HwTypeValues("disk_controller") 
      /**
      Enclosure
      */
      public static let enclosure = HwTypeValues("enclosure") 
      /**
      Fan
      */
      public static let fan = HwTypeValues("fan") 
      /**
      GPU
      */
      public static let gpu = HwTypeValues("gpu") 
      /**
      Logical disk
      */
      public static let logicalDisk = HwTypeValues("logical_disk") 
      /**
      Memory
      */
      public static let memory = HwTypeValues("memory") 
      /**
      Network
      */
      public static let network = HwTypeValues("network") 
      /**
      Physical disk
      */
      public static let physicalDisk = HwTypeValues("physical_disk") 
      /**
      Power supply
      */
      public static let powerSupply = HwTypeValues("power_supply") 
      /**
      Tape drive
      */
      public static let tapeDrive = HwTypeValues("tape_drive") 
      /**
      Temperature
      */
      public static let temperature = HwTypeValues("temperature") 
      /**
      Voltage
      */
      public static let voltage = HwTypeValues("voltage") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}