/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Linux: String {
    /**
     The Linux Slab memory state
      // Examples
      attributes[.linuxMemorySlabState] = reclaimable
      attributes[.linuxMemorySlabState] = unreclaimable
     - Requires: Value should be one of [`/output/Attributes/Linux_attributes.swift.LinuxMemorySlabStateValues`](x-source-tag://otelLinuxMemorySlabStateValues) (of type `String`)
    */
    case linuxMemorySlabState = "linux.memory.slab.state"


    /** 
      The Linux Slab memory state
    */
    /// - Tag: otelLinuxMemorySlabStateValues
    public struct LinuxMemorySlabStateValues: CustomStringConvertible {
      public static let reclaimable = LinuxMemorySlabStateValues("reclaimable") 
      public static let unreclaimable = LinuxMemorySlabStateValues("unreclaimable") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}