/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Nodejs: String {
    /**
     The state of event loop time.
     - Requires: Value should be one of [`/output/Attributes/Nodejs_attributes.swift.EventloopStateValues`](x-source-tag://otelEventloopStateValues) (of type `String`)
    */
    case eventloopState = "nodejs.eventloop.state"


    /** 
      The state of event loop time.
    */
    /// - Tag: otelEventloopStateValues
    public struct EventloopStateValues: CustomStringConvertible {
      /**
      Active time.
      */
      public static let active = EventloopStateValues("active") 
      /**
      Idle time.
      */
      public static let idle = EventloopStateValues("idle") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}