/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Nodejs: String {
    /**
     The state of event loop time.
     - Requires: Value should be one of [`/output/Attributes/Nodejs_attributes.swift.NodejsEventloopStateValues`](x-source-tag://otelNodejsEventloopStateValues) (of type `String`)
    */
    case nodejsEventloopState = "nodejs.eventloop.state"


    /** 
      The state of event loop time.
    */
    /// - Tag: otelNodejsEventloopStateValues
    public struct NodejsEventloopStateValues: CustomStringConvertible {
      /**
      Active time.
      */
      public static let active = NodejsEventloopStateValues("active") 
      /**
      Idle time.
      */
      public static let idle = NodejsEventloopStateValues("idle") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}