/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Openai: String {
    /**
     The service tier requested. May be a specific tier, default, or auto.
      // Examples
      attributes[.openaiRequestServiceTier] = auto
      attributes[.openaiRequestServiceTier] = default
     - Requires: Value should be one of [`/output/Attributes/Openai_attributes.swift.OpenaiRequestServiceTierValues`](x-source-tag://otelOpenaiRequestServiceTierValues) (of type `String`)
    */
    case openaiRequestServiceTier = "openai.request.service_tier"

    /**
     The service tier used for the response.
      // Examples
      attributes[.openaiResponseServiceTier] = "scale"
      attributes[.openaiResponseServiceTier] = "default"
     - Requires: Value type should be `String`
    */
    case openaiResponseServiceTier = "openai.response.service_tier"

    /**
     A fingerprint to track any eventual change in the Generative AI environment.
      // Examples
      attributes[.openaiResponseSystemFingerprint] = "fp_44709d6fcb"
     - Requires: Value type should be `String`
    */
    case openaiResponseSystemFingerprint = "openai.response.system_fingerprint"


    /** 
      The service tier requested. May be a specific tier, default, or auto.
    */
    /// - Tag: otelOpenaiRequestServiceTierValues
    public struct OpenaiRequestServiceTierValues: CustomStringConvertible {
      /**
      The system will utilize scale tier credits until they are exhausted.
      */
      public static let auto = OpenaiRequestServiceTierValues("auto") 
      /**
      The system will utilize the default scale tier.
      */
      public static let _default = OpenaiRequestServiceTierValues("default") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}