/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Profile: String {
    /**
     Describes the interpreter or compiler of a single frame.
      // Examples
      attributes[.profileFrameType] = cpython
     - Requires: Value should be one of [`/output/Attributes/Profile_attributes.swift.ProfileFrameTypeValues`](x-source-tag://otelProfileFrameTypeValues) (of type `String`)
    */
    case profileFrameType = "profile.frame.type"


    /** 
      Describes the interpreter or compiler of a single frame.
    */
    /// - Tag: otelProfileFrameTypeValues
    public struct ProfileFrameTypeValues: CustomStringConvertible {
      /**
      [.NET](https://wikipedia.org/wiki/.NET)
      */
      public static let dotnet = ProfileFrameTypeValues("dotnet") 
      /**
      [JVM](https://wikipedia.org/wiki/Java_virtual_machine)
      */
      public static let jvm = ProfileFrameTypeValues("jvm") 
      /**
      [Kernel](https://wikipedia.org/wiki/Kernel_(operating_system))
      */
      public static let kernel = ProfileFrameTypeValues("kernel") 
      /**
      Can be one of but not limited to [C](https://wikipedia.org/wiki/C_(programming_language)), [C++](https://wikipedia.org/wiki/C%2B%2B), [Go](https://wikipedia.org/wiki/Go_(programming_language)) or [Rust](https://wikipedia.org/wiki/Rust_(programming_language)). If possible, a more precise value MUST be used.
      */
      public static let native = ProfileFrameTypeValues("native") 
      /**
      [Perl](https://wikipedia.org/wiki/Perl)
      */
      public static let perl = ProfileFrameTypeValues("perl") 
      /**
      [PHP](https://wikipedia.org/wiki/PHP)
      */
      public static let php = ProfileFrameTypeValues("php") 
      /**
      [Python](https://wikipedia.org/wiki/Python_(programming_language))
      */
      public static let cpython = ProfileFrameTypeValues("cpython") 
      /**
      [Ruby](https://wikipedia.org/wiki/Ruby_(programming_language))
      */
      public static let ruby = ProfileFrameTypeValues("ruby") 
      /**
      [V8JS](https://wikipedia.org/wiki/V8_(JavaScript_engine))
      */
      public static let v8js = ProfileFrameTypeValues("v8js") 
      /**
      [Erlang](https://en.wikipedia.org/wiki/BEAM_(Erlang_virtual_machine))
      */
      public static let beam = ProfileFrameTypeValues("beam") 
      /**
      [Go](https://wikipedia.org/wiki/Go_(programming_language)),
      */
      public static let go = ProfileFrameTypeValues("go") 
      /**
      [Rust](https://wikipedia.org/wiki/Rust_(programming_language))
      */
      public static let rust = ProfileFrameTypeValues("rust") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}