/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Session: String {
    /**
     A unique id to identify a session.
      // Examples
  
   attributes[.sessionId] = "00112233-4455-6677-8899-aabbccddeeff"
     - Requires: Value type should be `String`
    */
    case sessionId = "session.id"

    /**
     The previous `session.id` for this user, when known.
      // Examples
  
   attributes[.sessionPreviousId] = "00112233-4455-6677-8899-aabbccddeeff"
     - Requires: Value type should be `String`
    */
    case sessionPreviousId = "session.previous_id"

  }
}