/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Signalr: String {
    /**
     SignalR HTTP connection closure status.
      // Examples
      attributes[.signalrConnectionStatus] = app_shutdown
      attributes[.signalrConnectionStatus] = timeout
     - Requires: Value should be one of [`/output/Attributes/Signalr_attributes.swift.SignalrConnectionStatusValues`](x-source-tag://otelSignalrConnectionStatusValues) (of type `String`)
    */
    case signalrConnectionStatus = "signalr.connection.status"

    /**
     [SignalR transport type](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md)
      // Examples
      attributes[.signalrTransport] = web_sockets
      attributes[.signalrTransport] = long_polling
     - Requires: Value should be one of [`/output/Attributes/Signalr_attributes.swift.SignalrTransportValues`](x-source-tag://otelSignalrTransportValues) (of type `String`)
    */
    case signalrTransport = "signalr.transport"


    /** 
      SignalR HTTP connection closure status.
    */
    /// - Tag: otelSignalrConnectionStatusValues
    public struct SignalrConnectionStatusValues: CustomStringConvertible {
      /**
      The connection was closed normally.
      */
      public static let normalClosure = SignalrConnectionStatusValues("normal_closure") 
      /**
      The connection was closed due to a timeout.
      */
      public static let timeout = SignalrConnectionStatusValues("timeout") 
      /**
      The connection was closed because the app is shutting down.
      */
      public static let appShutdown = SignalrConnectionStatusValues("app_shutdown") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      [SignalR transport type](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md)
    */
    /// - Tag: otelSignalrTransportValues
    public struct SignalrTransportValues: CustomStringConvertible {
      /**
      ServerSentEvents protocol
      */
      public static let serverSentEvents = SignalrTransportValues("server_sent_events") 
      /**
      LongPolling protocol
      */
      public static let longPolling = SignalrTransportValues("long_polling") 
      /**
      WebSockets protocol
      */
      public static let webSockets = SignalrTransportValues("web_sockets") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}