/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Source: String {
    /**
     Source address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
      // Examples
      attributes[.sourceAddress] = "source.example.com"
      attributes[.sourceAddress] = "10.1.2.80"
      attributes[.sourceAddress] = "/tmp/my.sock"
     - Note: When observed from the destination side, and when communicating through an intermediary, `source.address` SHOULD represent the source address behind any intermediaries, for example proxies, if it's available.
     - Requires: Value type should be `String`
    */
    case sourceAddress = "source.address"

    /**
     Source port number
      // Examples
      attributes[.sourcePort] = 3389
      attributes[.sourcePort] = 2888
     - Requires: Value type should be `Int`
    */
    case sourcePort = "source.port"

  }
}