/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum System: String {
    /**
     Deprecated, use `cpu.logical_number` instead.
      // Examples
      attributes[.systemCpuLogicalNumber] = 1
     - Requires: Value type should be `Int`
    */
    case cpuLogicalNumber = "system.cpu.logical_number"

    /**
     The device identifier
      // Examples
      attributes[.systemDevice] = "(identifier)"
     - Requires: Value type should be `String`
    */
    case device = "system.device"

    /**
     The filesystem mode
      // Examples
      attributes[.systemFilesystemMode] = "rw, ro"
     - Requires: Value type should be `String`
    */
    case fileMode = "system.filesystem.mode"

    /**
     The filesystem mount path
      // Examples
      attributes[.systemFilesystemMountpoint] = "/mnt/data"
     - Requires: Value type should be `String`
    */
    case fileMountpoint = "system.filesystem.mountpoint"

    /**
     The filesystem state
      // Examples
      attributes[.systemFilesystemState] = used
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.FileStateValues`](x-source-tag://otelFileStateValues) (of type `String`)
    */
    case fileState = "system.filesystem.state"

    /**
     The filesystem type
      // Examples
      attributes[.systemFilesystemType] = ext4
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.FileTypeValues`](x-source-tag://otelFileTypeValues) (of type `String`)
    */
    case fileType = "system.filesystem.type"

    /**
     The memory state
      // Examples
      attributes[.systemMemoryState] = free
      attributes[.systemMemoryState] = cached
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.MemoryStateValues`](x-source-tag://otelMemoryStateValues) (of type `String`)
    */
    case memoryState = "system.memory.state"

    /**
     The paging access direction
      // Examples
      attributes[.systemPagingDirection] = in
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.PagingDirectionValues`](x-source-tag://otelPagingDirectionValues) (of type `String`)
    */
    case pagingDirection = "system.paging.direction"

    /**
     The memory paging state
      // Examples
      attributes[.systemPagingState] = free
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.PagingStateValues`](x-source-tag://otelPagingStateValues) (of type `String`)
    */
    case pagingState = "system.paging.state"

    /**
     The memory paging type
      // Examples
      attributes[.systemPagingType] = minor
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.PagingTypeValues`](x-source-tag://otelPagingTypeValues) (of type `String`)
    */
    case pagingType = "system.paging.type"

    /**
     The process state, e.g., [Linux Process State Codes](https://man7.org/linux/man-pages/man1/ps.1.html#PROCESS_STATE_CODES)
      // Examples
      attributes[.systemProcessStatus] = running
     - Requires: Value should be one of [`/output/Attributes/System_attributes.swift.ProcessStatusValues`](x-source-tag://otelProcessStatusValues) (of type `String`)
    */
    case processStatus = "system.process.status"


    /** 
      The filesystem state
    */
    /// - Tag: otelFileStateValues
    public struct FileStateValues: CustomStringConvertible {
      public static let used = FileStateValues("used") 
      public static let free = FileStateValues("free") 
      public static let reserved = FileStateValues("reserved") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The filesystem type
    */
    /// - Tag: otelFileTypeValues
    public struct FileTypeValues: CustomStringConvertible {
      public static let fat32 = FileTypeValues("fat32") 
      public static let exfat = FileTypeValues("exfat") 
      public static let ntfs = FileTypeValues("ntfs") 
      public static let refs = FileTypeValues("refs") 
      public static let hfsplus = FileTypeValues("hfsplus") 
      public static let ext4 = FileTypeValues("ext4") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The memory state
    */
    /// - Tag: otelMemoryStateValues
    public struct MemoryStateValues: CustomStringConvertible {
      /**
      Actual used virtual memory in bytes.
      */
      public static let used = MemoryStateValues("used") 
      public static let free = MemoryStateValues("free") 
      public static let buffers = MemoryStateValues("buffers") 
      public static let cached = MemoryStateValues("cached") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The paging access direction
    */
    /// - Tag: otelPagingDirectionValues
    public struct PagingDirectionValues: CustomStringConvertible {
      public static let _in = PagingDirectionValues("in") 
      public static let out = PagingDirectionValues("out") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The memory paging state
    */
    /// - Tag: otelPagingStateValues
    public struct PagingStateValues: CustomStringConvertible {
      public static let used = PagingStateValues("used") 
      public static let free = PagingStateValues("free") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The memory paging type
    */
    /// - Tag: otelPagingTypeValues
    public struct PagingTypeValues: CustomStringConvertible {
      public static let major = PagingTypeValues("major") 
      public static let minor = PagingTypeValues("minor") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      The process state, e.g., [Linux Process State Codes](https://man7.org/linux/man-pages/man1/ps.1.html#PROCESS_STATE_CODES)
    */
    /// - Tag: otelProcessStatusValues
    public struct ProcessStatusValues: CustomStringConvertible {
      public static let running = ProcessStatusValues("running") 
      public static let sleeping = ProcessStatusValues("sleeping") 
      public static let stopped = ProcessStatusValues("stopped") 
      public static let defunct = ProcessStatusValues("defunct") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}