/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum Thread: String {
    /**
     Current "managed" thread ID (as opposed to OS thread ID).
      // Examples
  
   attributes[.threadId] = 42
     - Requires: Value type should be `Int`
    */
    case id = "thread.id"

    /**
     Current thread name.
      // Examples
  
   attributes[.threadName] = "main"
     - Requires: Value type should be `String`
    */
    case name = "thread.name"

  }
}