/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  enum User: String {
    /**
     User email address.
      // Examples
      attributes[.userEmail] = "a.einstein@example.com"
     - Requires: Value type should be `String`
    */
    case userEmail = "user.email"

    /**
     User's full name
      // Examples
      attributes[.userFullName] = "Albert Einstein"
     - Requires: Value type should be `String`
    */
    case userFullName = "user.full_name"

    /**
     Unique user hash to correlate information for a user in anonymized form.
      // Examples
      attributes[.userHash] = "364fc68eaf4c8acec74a4e52d7d1feaa"
     - Note: Useful if `user.id` or `user.name` contain confidential information and cannot be used.
     - Requires: Value type should be `String`
    */
    case userHash = "user.hash"

    /**
     Unique identifier of the user.
      // Examples
      attributes[.userId] = "S-1-5-21-202424912787-2692429404-2351956786-1000"
     - Requires: Value type should be `String`
    */
    case userId = "user.id"

    /**
     Short name or login/username of the user.
      // Examples
      attributes[.userName] = "a.einstein"
     - Requires: Value type should be `String`
    */
    case userName = "user.name"

    /**
     Array of user roles at the time of the event.
      // Examples
      attributes[.userRoles] = ["admin", "reporting_user"]
     - Requires: Value type should be `[String]`
    */
    case userRoles = "user.roles"

  }
}